## Data Importing

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Bengaluru_House_Data.csv.xls')
display(df)

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00
...,...,...,...,...,...,...,...,...,...
13315,Built-up Area,Ready To Move,Whitefield,5 Bedroom,ArsiaEx,3453,4.0,0.0,231.00
13316,Super built-up Area,Ready To Move,Richards Town,4 BHK,NaN,3600,5.0,NaN,400.00
13317,Built-up Area,Ready To Move,Raja Rajeshwari Nagar,2 BHK,Mahla T,1141,2.0,1.0,60.00
13318,Super built-up Area,18-Jun,Padmanabhanagar,4 BHK,SollyCl,4689,4.0,1.0,488.00
13319,Super built-up Area,Ready To Move,Doddathoguru,1 BHK,NaN,550,1.0,1.0,17.00

## Exploratory Data Analysis

In [ ]:
df.shape

(13320, 9)

In [ ]:
df.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [ ]:
df.describe()

               bath       balcony         price
count  13247.000000  12711.000000  13320.000000
mean       2.692610      1.584376    112.565627
std        1.341458      0.817263    148.971674
min        1.000000      0.000000      8.000000
25%        2.000000      1.000000     50.000000
50%        2.000000      2.000000     72.000000
75%        3.000000      2.000000    120.000000
max       40.000000      3.000000   3600.000000

In [ ]:
for column in df.columns:
    print(df[column].value_counts())
    print("*"*20)

area_type
Super built-up  Area    8790
Built-up  Area          2418
Plot  Area              2025
Carpet  Area              87
Name: count, dtype: int64
********************
availability
Ready To Move    10581
18-Dec             307
18-May             295
18-Apr             271
18-Aug             200
                 ...
16-Oct               1
17-Jan               1
16-Nov               1
16-Jan               1
14-Jul               1
Name: count, Length: 81, dtype: int64
********************
location
Whitefield                         540
Sarjapur  Road                     399
Electronic City                    302
Kanakpura Road                     273
Thanisandra                        234
                                  ...
3rd Stage Raja Rajeshwari Nagar      1
Chuchangatta Colony                  1
Electronic City Phase 1,             1
Chikbasavanapura                     1
Abshot Layout                        1
Name: count, Length: 1305, dtype: int64
********************
size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
10 BHK           2
11 Bedroom       2
27 BHK           1
19 BHK           1
43 Bedroom       1
16 BHK           1
14 BHK           1
12 Bedroom       1
13 BHK           1
18 Bedroom       1
Name: count, dtype: int64
********************
society
GrrvaGr    80
PrarePa    76
Sryalan    59
Prtates    59
GMown E    56
           ..
SLtalry     1
Rencyes     1
DiaveEn     1
Suiumy      1
Amionce     1
Name: count, Length: 2688, dtype: int64
********************
total_sqft
1200           843
1100           221
1500           205
2400           196
600            180
              ...
2920             1
5665.84          1
1369             1
7150             1
1200 - 1470      1
Name: count, Length: 2117, dtype: int64
********************
bath
2.0     6908
3.0     3286
4.0     1226
1.0      788
5.0      524
6.0      273
7.0      102
8.0       64
9.0       43
10.0      13
12.0       7
11.0       3
13.0       3
16.0       2
27.0       1
14.0       1
40.0       1
15.0       1
18.0       1
Name: count, dtype: int64
********************
balcony
2.0    5113
1.0    4897
3.0    1672
0.0    1029
Name: count, dtype: int64
********************
price
75.00    310
65.00    302
55.00    275
60.00    270
45.00    240
        ...
43.04      1
61.11      1
46.56      1
42.54      1
47.35      1
Name: count, Length: 1994, dtype: int64
********************

In [ ]:
df.isnull().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

## Data Preprocessing

In [ ]:
df.drop(columns=['area_type','availability','society','balcony'],inplace=True)

In [ ]:
df.describe()

               bath         price
count  13247.000000  13320.000000
mean       2.692610    112.565627
std        1.341458    148.971674
min        1.000000      8.000000
25%        2.000000     50.000000
50%        2.000000     72.000000
75%        3.000000    120.000000
max       40.000000   3600.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13319 non-null  object
 1   size        13304 non-null  object
 2   total_sqft  13320 non-null  object
 3   bath        13247 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB

In [ ]:
df.isnull().sum()

location       1
size          16
total_sqft     0
bath          73
price          0
dtype: int64

In [ ]:
df['location'].value_counts()

location
Whitefield                         540
Sarjapur  Road                     399
Electronic City                    302
Kanakpura Road                     273
Thanisandra                        234
                                  ...
3rd Stage Raja Rajeshwari Nagar      1
Chuchangatta Colony                  1
Electronic City Phase 1,             1
Chikbasavanapura                     1
Abshot Layout                        1
Name: count, Length: 1305, dtype: int64

In [ ]:
df['location'] = df['location'].fillna('Sarjapur Road')

In [ ]:
df.isnull().sum()

location       0
size          16
total_sqft     0
bath          73
price          0
dtype: int64

## Data Cleaning

In [ ]:
df['size'].value_counts()

size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
10 BHK           2
11 Bedroom       2
27 BHK           1
19 BHK           1
43 Bedroom       1
16 BHK           1
14 BHK           1
12 Bedroom       1
13 BHK           1
18 Bedroom       1
Name: count, dtype: int64

In [ ]:
df['size'] = df['size'].fillna('2 BHK')

In [ ]:
df.isnull().sum()

location       0
size           0
total_sqft     0
bath          73
price          0
dtype: int64

In [ ]:
df['bath'] = df['bath'].fillna(df['bath'].median())

In [ ]:
df.isnull().sum()

location      0
size          0
total_sqft    0
bath          0
price         0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13320 non-null  object
 1   size        13320 non-null  object
 2   total_sqft  13320 non-null  object
 3   bath        13320 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB

In [ ]:
df['bhk'] = df['size'].str.split().str.get(0).astype(int)

In [ ]:
df.drop(columns = ['size'], inplace = True)

In [ ]:
df.head()

                   location total_sqft  bath   price  bhk
0  Electronic City Phase II       1056   2.0   39.07    2
1          Chikka Tirupathi       2600   5.0  120.00    4
2               Uttarahalli       1440   2.0   62.00    3
3        Lingadheeranahalli       1521   3.0   95.00    3
4                  Kothanur       1200   2.0   51.00    2

In [ ]:
df['bhk'].value_counts().sort_index()

bhk
1      656
2     5544
3     4857
4     1417
5      356
6      221
7      100
8       89
9       54
10      14
11       4
12       1
13       1
14       1
16       1
18       1
19       1
27       1
43       1
Name: count, dtype: int64

In [ ]:
df['bhk'] >= 12

0        False
1        False
2        False
3        False
4        False
         ...
13315    False
13316    False
13317    False
13318    False
13319    False
Name: bhk, Length: 13320, dtype: bool

In [ ]:
df.drop(df[df['bhk'] >= 12].index, inplace = True)

In [ ]:
df['bhk'].value_counts().sort_index()

bhk
1      656
2     5544
3     4857
4     1417
5      356
6      221
7      100
8       89
9       54
10      14
11       4
Name: count, dtype: int64

In [ ]:
df['total_sqft'].unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      dtype=object)

In [ ]:
def convertRange(x):

    temp = x.split('-')

    if len(temp) == 2:
        return (float(temp[0]) + float(temp[1]))/2

    try:
        return float(x)
    except:
        return None

In [ ]:
df['total_sqft'] = df['total_sqft'].apply(convertRange)

In [ ]:
df['total_sqft'].unique()

array([1056. , 2600. , 1440. , ..., 1258.5,  774. , 4689. ])

In [ ]:
df['price_per_sqft'] = df['price'] * 100000 / df['total_sqft']

In [ ]:
df['price_per_sqft']

0         3699.810606
1         4615.384615
2         4305.555556
3         6245.890861
4         4250.000000
             ...
13315     6689.834926
13316    11111.111111
13317     5258.545136
13318    10407.336319
13319     3090.909091
Name: price_per_sqft, Length: 13312, dtype: float64

In [ ]:
df['location'].value_counts()

location
Whitefield                                  540
Sarjapur  Road                              399
Electronic City                             302
Kanakpura Road                              273
Thanisandra                                 234
                                           ...
Maheswari Nagar                               1
Hsr layout sector3                            1
Thyagraj Nagar                                1
Banagirinagar                                 1
Banashankari 3rd stage, Vivekanandanagar      1
Name: count, Length: 1301, dtype: int64

In [ ]:
df.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  13266.000000  13312.000000  13312.000000  13312.000000    1.326600e+04
mean    1558.116820      2.679087    112.420684      2.792293    7.904313e+03
std     1234.839073      1.256911    148.835619      1.198962    1.064614e+05
min        1.000000      1.000000      8.000000      1.000000    2.678298e+02
25%     1100.000000      2.000000     50.000000      2.000000    4.266667e+03
50%     1276.000000      2.000000     72.000000      3.000000    5.433101e+03
75%     1680.000000      3.000000    120.000000      3.000000    7.308979e+03
max    52272.000000     14.000000   3600.000000     11.000000    1.200000e+07

In [ ]:
df['location'].value_counts()

location
Whitefield                                  540
Sarjapur  Road                              399
Electronic City                             302
Kanakpura Road                              273
Thanisandra                                 234
                                           ...
Maheswari Nagar                               1
Hsr layout sector3                            1
Thyagraj Nagar                                1
Banagirinagar                                 1
Banashankari 3rd stage, Vivekanandanagar      1
Name: count, Length: 1301, dtype: int64

In [ ]:
df['location'] = df['location'].apply(lambda x: x.strip())

In [ ]:
df['location'].value_counts()

location
Whitefield                           541
Sarjapur  Road                       399
Electronic City                      304
Kanakpura Road                       273
Thanisandra                          237
                                    ...
Beml layout, Rajarajeshwari nagar      1
Duddanahalli                           1
Doddanakunte                           1
Jogupalya                              1
Subhash Nagar                          1
Name: count, Length: 1290, dtype: int64

In [ ]:
location_count = df['location'].value_counts()

In [ ]:
df['location'].value_counts()

location
Whitefield                           541
Sarjapur  Road                       399
Electronic City                      304
Kanakpura Road                       273
Thanisandra                          237
                                    ...
Beml layout, Rajarajeshwari nagar      1
Duddanahalli                           1
Doddanakunte                           1
Jogupalya                              1
Subhash Nagar                          1
Name: count, Length: 1290, dtype: int64

In [ ]:
location_count_less_10 = location_count[location_count <= 10]
location_count_less_10

location
Nagadevanahalli                      10
Gunjur Palya                         10
Dodsworth Layout                     10
Ganga Nagar                          10
BTM 1st Stage                        10
                                     ..
Beml layout, Rajarajeshwari nagar     1
Duddanahalli                          1
Doddanakunte                          1
Jogupalya                             1
Subhash Nagar                         1
Name: count, Length: 1049, dtype: int64

In [ ]:
df['location'] = df['location'].apply(lambda x: 'other' if x in location_count_less_10 else x)

In [ ]:
df['location'].value_counts()

location
other                        2880
Whitefield                    541
Sarjapur  Road                399
Electronic City               304
Kanakpura Road                273
                             ...
Tindlu                         11
Marsur                         11
2nd Phase Judicial Layout      11
Thyagaraja Nagar               11
HAL 2nd Stage                  11
Name: count, Length: 242, dtype: int64

In [ ]:
df.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  13266.000000  13312.000000  13312.000000  13312.000000    1.326600e+04
mean    1558.116820      2.679087    112.420684      2.792293    7.904313e+03
std     1234.839073      1.256911    148.835619      1.198962    1.064614e+05
min        1.000000      1.000000      8.000000      1.000000    2.678298e+02
25%     1100.000000      2.000000     50.000000      2.000000    4.266667e+03
50%     1276.000000      2.000000     72.000000      3.000000    5.433101e+03
75%     1680.000000      3.000000    120.000000      3.000000    7.308979e+03
max    52272.000000     14.000000   3600.000000     11.000000    1.200000e+07

In [ ]:
(df['total_sqft'] / df['bhk']).describe()

count    13266.000000
mean       575.282851
std        388.201655
min          0.250000
25%        473.541667
50%        552.500000
75%        625.000000
max      26136.000000
dtype: float64

In [ ]:
df = df[((df['total_sqft'] / df['bhk']) >= 300)]

In [ ]:
df.head()

                   location  total_sqft  bath   price  bhk  price_per_sqft
0  Electronic City Phase II      1056.0   2.0   39.07    2     3699.810606
1          Chikka Tirupathi      2600.0   5.0  120.00    4     4615.384615
2               Uttarahalli      1440.0   2.0   62.00    3     4305.555556
3        Lingadheeranahalli      1521.0   3.0   95.00    3     6245.890861
4                  Kothanur      1200.0   2.0   51.00    2     4250.000000

In [ ]:
sqft_sort = df['total_sqft'].value_counts()

In [ ]:
display(sqft_sort)

total_sqft
1200.00    664
1100.00    213
2400.00    193
1500.00    190
1000.00    151
          ...
6688.00      1
1331.95      1
2872.00      1
1648.00      1
2295.00      1
Name: count, Length: 1960, dtype: int64

In [ ]:
sqft_sort_less_1000 = sqft_sort[sqft_sort >= np.mean(sqft_sort)]
sqft_sort_less_1000

total_sqft
1200.0    664
1100.0    213
2400.0    193
1500.0    190
1000.0    151
         ...
880.0       7
982.0       7
1840.0      7
1272.0      7
1427.0      7
Name: count, Length: 372, dtype: int64

In [ ]:
df.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  12528.000000  12528.000000  12528.000000  12528.000000    12528.000000
mean    1593.587862      2.557631    111.334330      2.648946     6304.142100
std     1258.668794      1.067245    152.031936      0.965025     4162.549406
min      300.000000      1.000000      8.440000      1.000000      267.829813
25%     1116.000000      2.000000     49.000000      2.000000     4210.526316
50%     1300.000000      2.000000     70.000000      3.000000     5294.117647
75%     1700.000000      3.000000    115.000000      3.000000     6916.666667
max    52272.000000     14.000000   3600.000000     11.000000   176470.588235

In [ ]:
def remove_outliers_sqft(df):
  if df.empty:
    print("DataFrame is empty, cannot perform outlier removal.")
    return pd.DataFrame()

  df_output = pd.DataFrame()
  for key, subdf in df.groupby('location'):
    m = np.mean(subdf.price_per_sqft)
    st = np.std(subdf.price_per_sqft)

    gen_df = subdf[(subdf.price_per_sqft > (m - st)) & (subdf.price_per_sqft <= (m + st))]
    df_output = pd.concat([df_output, gen_df], ignore_index = True)
  return df_output
df = remove_outliers_sqft(df)

In [ ]:
df.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  10299.000000  10299.000000  10299.000000  10299.000000    10299.000000
mean    1507.235819      2.469366     91.223995      2.572580     5659.135602
std      875.945163      0.964866     86.213748      0.881969     2265.986759
min      300.000000      1.000000     10.000000      1.000000     1250.000000
25%     1110.000000      2.000000     49.000000      2.000000     4244.830457
50%     1286.000000      2.000000     67.000000      2.000000     5175.600739
75%     1650.000000      3.000000    100.000000      3.000000     6428.571429
max    30400.000000     12.000000   2200.000000     11.000000    24509.803922

In [ ]:
df.shape

(10299, 6)

In [ ]:
def bhk_outlier_remover(df):
  exclude_indices = np.array([])
  for location, location_df in df.groupby('location'):
    bhk_stats = {}
    for bhk, bhk_df in location_df.groupby('bhk'):
      bhk_stats[bhk] = {
          'mean' : np.mean(bhk_df.price_per),
          'std' : np.std(bhk_df.price_per_sqft),
          'count' : bhk_df.shape[0]
      }
    for bhk, bhk_df in location_df.groupby('bhk'):
      stats = bhk_stats.get(bhk - 1)
      if stats and stats['count'] > 5:
        exclude_indices = np.append(exclude_indices, bhk_df[bhk_df.price_per_sqft < (stats['mean'])].index.values)
  return df.drop(exclude_indices, axis = 'index')

In [ ]:
df.shape

(10299, 6)

In [ ]:
df.drop(columns = ['price_per_sqft'], inplace = True)

In [ ]:
df

                  location  total_sqft  bath   price  bhk
0      1st Block Jayanagar      2850.0   4.0  428.00    4
1      1st Block Jayanagar      1630.0   3.0  194.00    3
2      1st Block Jayanagar      1875.0   2.0  235.00    3
3      1st Block Jayanagar      1200.0   2.0  130.00    3
4      1st Block Jayanagar      1235.0   2.0  148.00    2
...                    ...         ...   ...     ...  ...
10294                other      1353.0   2.0  110.00    2
10295                other       812.0   1.0   26.00    1
10296                other      1440.0   2.0   63.93    3
10297                other      1075.0   2.0   48.00    2
10298                other      3600.0   5.0  400.00    4

[10299 rows x 5 columns]

## Dividing Data For Training And Testing

In [ ]:
df.head()

              location  total_sqft  bath  price  bhk
0  1st Block Jayanagar      2850.0   4.0  428.0    4
1  1st Block Jayanagar      1630.0   3.0  194.0    3
2  1st Block Jayanagar      1875.0   2.0  235.0    3
3  1st Block Jayanagar      1200.0   2.0  130.0    3
4  1st Block Jayanagar      1235.0   2.0  148.0    2

In [ ]:
df.to_csv("House_Price_Clean_Data.csv")

In [ ]:
from google.colab import files
files.download('House_Price_Clean_Data.csv')

In [ ]:
X = df.drop(columns = ['price'])
y = df['price']

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
print(X_train.shape)
print(X_test.shape)

(8239, 4)
(2060, 4)

## Appling Linear Regression

In [ ]:
column_trans = make_column_transformer((OneHotEncoder(sparse_output = False), ['location']), remainder = 'passthrough')

In [ ]:
scaler = StandardScaler()

In [ ]:
lr = LinearRegression()

In [ ]:
pipelr = make_pipeline(column_trans, scaler, lr)

In [ ]:
pipelr.fit(X_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()),
                ('linearregression', LinearRegression())])

In [ ]:
y_pred_lr = pipelr.predict(X_test)

In [ ]:
r2_score = r2_score(y_test, y_pred_lr)

In [ ]:
print(r2_score)

0.8391046032979619

## Applying Lasso

In [ ]:
lso = Lasso()

In [ ]:
pipel = make_pipeline(column_trans, scaler, lso)

In [ ]:
pipel.fit(X_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()), ('lasso', Lasso())])

In [ ]:
y_pred_l = pipel.predict(X_test)

In [ ]:
from sklearn.metrics import r2_score
r2_score = r2_score(y_test, y_pred_l)

In [ ]:
print(r2_score)

0.8321399191964041

## Applying Ridge

In [ ]:
rge = Ridge()

In [ ]:
piper = make_pipeline(column_trans, scaler, rge)

In [ ]:
piper.fit(X_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/compose/_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()), ('ridge', Ridge())])

In [ ]:
y_pred_r = piper.predict(X_test)

In [ ]:
from sklearn.metrics import r2_score
r2_score = r2_score(y_test, y_pred_r)

In [ ]:
print(r2_score)

0.8391033521819181

In [ ]:
from sklearn.metrics import r2_score

print("Linear Regression ->\n", r2_score(y_test, y_pred_lr),"\n")
print("Lasso ->\n", r2_score(y_test, y_pred_l),"\n")
print("Ridge ->\n", r2_score(y_test, y_pred_r),"\n")

Linear Regression ->
 0.8391046032979619

Lasso ->
 0.8321399191964041

Ridge ->
 0.8391033521819181

## Deployment

In [ ]:
import pickle

In [ ]:
pickle.dump(piper, open('RidgeModel.pkl', 'wb'))

In [ ]:
from google.colab import files₹₹
files.download('RidgeModel.pkl')